name: User Management

on:
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
        
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: snok/install-poetry@v1
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        
    - name: Lint
      run: |
        poetry run black .
        poetry run isort .

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Check running containers
      run: docker ps -a
        
    - name: Test with pytest
      run: |
        docker compose -f "docker-compose.yml" exec -T web bash -c "poetry run pytest"
